Trennung von Ebermannstadt und Forchheim
FreifunkFranken/community.franken.freifunk.net pull request #11
Opened 2017-09-02 18:22 UTC by MaretaDagostino

Vor der Hoodtrennung hatte die Community Ebermannstadt die Hood Forchheim, nun haben sie eine eigene Hood. Außerdem wurde OLSR inzwischen durch Babel abgelöst. (Miki)

2017-09-03 21:23 UTC, kratz00 requested changes

2017-09-03 21:23 UTC, kratz00 commented on communitys_franken.json
> +			},
Dieses Komma macht die JSON-Struktur kaputt.
Bitte teste deine Aenderungen.

2017-09-03 21:23 UTC, kratz00 commented on communitys_franken.json
> +			"contact" : {
Das _contact_ Objekt ist redundant, da es die selben Werte der Meta-Community enthaelt, bitte entfernen.

2017-09-03 21:23 UTC, kratz00 commented on communitys_franken.json
> +			"socialprojects": {
Haben Ebermannstadt und Forchheim, beide jeweils 2 soziale Projekte?

2017-09-04 09:13 UTC, kratz00 commented
> Apropos testen: Wie soll ich denn das testen? Der Freifunk.net Validator nimmt nur die Dateien an, die am Ende Dein Generator erzeugen würde...

1. Du haettest direkt die JSON Datei _communitys_franken.json_ validieren koennen
2. Du haettest versuchen koennen die Community-Dateien zu erzeugen, indem du das Skript _create_community_files.py_ ausgefuehrt haettest

2017-09-04 09:13 UTC, kratz00 approved these changes

2017-09-04 09:14 UTC, merged

2017-09-04 19:05 UTC, MaretaDagostino commented
Danke! Auch für die Tipps :-)

2017-09-04 20:26 UTC, kratz00 commented
Gern geschehen :smiley: 
Danke dir fuer deinen Patch!